
[env]
platform = teensy
board = teensy41
framework = arduino

[env:LPCtest]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial7
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41test/*.cpp>

[env:RATSECUtest]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial1
  -DRATSRS41

build_src_filter = 
  +<*.cpp>
  +<../examples/RS41test/*.cpp>

[env:LPCcsv]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial7
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41csv/*.cpp>

[env:RATSECUcsv]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial1
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41csv/*.cpp>


