
[env]
platform = teensy
board = teensy41
framework = arduino

[env:LPCtest]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial7
  -DRS41EN=32
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41test/*.cpp>

[env:ECUtest]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial1
  -DRS41EN=2
  -DRATSRS41
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41test/*.cpp>

[env:RPUtest]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial6
  -DRS41EN=41
  -DRATSRS41
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41test/*.cpp>

[env:LPCcsv]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial7
  -DRS41EN=32
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41csv/*.cpp>

[env:ECUcsv]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial1
  -DRS41EN=2
build_src_filter = 
  +<*.cpp>
  +<../examples/RS41csv/*.cpp>

[env:ECUpassthru]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial1
  -DRS41EN=2
build_src_filter = 
  +<*.cpp>
  +<../examples/PassThru/*.cpp>

[env:RPUpassthru]
build_flags = 
  ${env.build_flags}
  -DRS41SERIAL=Serial6
  -DRS41EN=41
build_src_filter = 
  +<*.cpp>
  +<../examples/PassThru/*.cpp>


